[build]
  command = "bun run build"
  publish = "dist"
  functions = "netlify/functions"
  [build.environment]
    NODE_VERSION = "20"
    BUN_VERSION = "1.0.26"
  [build.processing]
    skip_processing = false
  [build.processing.css]
    bundle = true
    minify = true
  [build.processing.js]
    bundle = true
    minify = true
  [build.processing.html]
    pretty_urls = true
  [build.processing.images]
    compress = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["bun"]
  included_files = ["package.json"]
  
[build.lifecycle]
  onInstall = "bun install --no-save --frozen-lockfile --timeout 120000"